#### Module 1: Exception Handling

- Simply put exceptions are error conditions which disrupt the normal flow of the program- Python allows for a simple and elegant way to handle exceptions

```sh
>>> 0/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
>>>
```

```sh
>>> try:
...     a = 0/0
... except:
...     print "Exception Happened"
...
Exception Happened
>>>
```

```sh
>>> try:
...     a = 10/20
... except:
...     print "Exception"
... else:
...     print "No Exception"
... finally:
...     print "Cleanup Code"
...
No Exception
Cleanup Code
>>>
```

```sh
>>> try:
...     a = 0/0
... except ZeroDivisionError:
...     print "Divide by Zero"
... except:
...     print "Unknown error"
...
Divide by Zero
>>>
```

```sh
>>> try:
...     a = 0/0
... except Exception as im:
...     print im
...
integer division or modulo by zero
>>>
```

###### Exercise
- Python allows for user defined exceptions
- Code up a demo which has a user defined exception and an example use case

```sh
➜  Lesson-9 git:(master) ✗ cat userdefined_exceptions.py
#!/usr/bin/python
# A python program to create user-defined exception

# class MyError is derived from super class Exception
class MyError(Exception):

    # Constructor or Initializer
    def __init__(self, value):
        self.value = value

    # __str__ is to print() the value
    def __str__(self):
        return(repr(self.value))

try:
    raise(MyError(3*2))

# Value of Exception is stored in error
except MyError as error:
    print('A New Exception occured: ',error.value)
➜  Lesson-9 git:(master) ✗
```

```sh
➜  Lesson-9 git:(master) ✗ ./userdefined_exceptions.py
('A New Exception occured: ', 6)
➜  Lesson-9 git:(master) ✗
```